### ISSUE TITLE
ability to run on raspberry pi

### ISSUE THREAD

**Issue by abauer** [EnsemblePlayer/player-client#5]

**Comment by abauer** [comment]
linked with #4

**Comment by abauer** [comment]
possibly solved with pygame - up to @TexasGamer to test on the pi

**Comment by abauer** [comment]
@TexasGamer ready for test

**Comment by abauer** [comment]
things that ensemble currently uses
- pygame - plays music
- ffmpeg - converts music
- youtube_dl - downloads YT songs
- gmusic api - downloads Google songs

**Comment by ThomasGaubert** [comment]
:shipit:
